title: <Lauren Zane> # your name (or website title) here
logo: "/images/IMG_3631.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student in the Putnam Lab at the University of Rhode Island 
  <br><br>
  Department of Biological and Environmental Science
  <br><br>
  <a href="https://twitter.com/laurennzane">View My Twitter Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
